# Generated by Django 5.2.13 on 2026-07-09 15:30

from django.db import migrations


def draft_to_accepted(apps, schema_editor):
    RepairOrder = apps.get_model('orders', 'RepairOrder')
    RepairOrder.objects.filter(status='draft').update(status='accepted')


def accepted_to_draft(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_repairorder_status'),
    ]

    operations = [
        migrations.RunPython(draft_to_accepted, accepted_to_draft),
    ]
