# Generated by Django 5.2.13 on 2026-10-05 19:10

from django.db import migrations, models


def _rename_status(apps, old, new):
    RepairOrder = apps.get_model('orders', 'RepairOrder')
    StatusHistory = apps.get_model('orders', 'StatusHistory')
    RepairOrder.objects.filter(status=old).update(status=new)
    # History keeps raw status keys, so it has to follow or old entries would show an unknown status.
    StatusHistory.objects.filter(old_status=old).update(old_status=new)
    StatusHistory.objects.filter(new_status=old).update(new_status=new)


def diagnosing_to_estimating(apps, schema_editor):
    _rename_status(apps, 'diagnosing', 'estimating')


def estimating_to_diagnosing(apps, schema_editor):
    _rename_status(apps, 'estimating', 'diagnosing')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_repairorder_estimated_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairorder',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('estimating', 'Estimating'), ('waiting_parts', 'Waiting for Parts'), ('in_progress', 'In Progress'), ('done', 'Done'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='accepted', max_length=20),
        ),
        migrations.RunPython(diagnosing_to_estimating, estimating_to_diagnosing),
    ]
