# Generated by Django 5.2.13 on 2026-04-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('bike_type', models.CharField(choices=[('road', 'Road'), ('mtb', 'Mountain'), ('city', 'City'), ('gravel', 'Gravel'), ('electric', 'Electric'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='customers.customer')),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
