# Generated by Django 5.2.13 on 2026-07-02 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bike',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
