# Generated by Django 5.2.13 on 2026-09-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_bike_photo_bike_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rodo_accepted',
            field=models.BooleanField(default=False, help_text='Klient podpisal zgode RODO na przetwarzanie danych i przechowywanie ich w systemie.', verbose_name='RODO zaakceptowane'),
        ),
    ]
