# Generated by Django 5.2.13 on 2026-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_rodo_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('bike', 'Rower'), ('winter', 'Sprzet zimowy')], db_index=True, default='bike', help_text='Rower albo sprzet zimowy (narty, snowboard, buty itp.).', max_length=10, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('road', 'Road'), ('mtb', 'Mountain'), ('city', 'City'), ('gravel', 'Gravel'), ('electric', 'Electric'), ('other', 'Other')], default='other', help_text='Dotyczy wylacznie rowerow. Dla sprzetu zimowego zawsze `other`.', max_length=20),
        ),
    ]
