# Generated by Django 5.2.13 on 2026-09-25 18:32

import apps.storage.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_bike_category_alter_bike_bike_type'),
        ('orders', '0009_remove_repairorder_bike'),
        ('storage', '0002_delete_legacy_storage_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Od')),
                ('end_date', models.DateField(help_text='Ostatni dzien pobytu, wlacznie.', verbose_name='Do')),
                ('status', models.CharField(choices=[('reserved', 'Zarezerwowane'), ('stored', 'W magazynie'), ('picked_up', 'Odebrane'), ('cancelled', 'Anulowane')], db_index=True, default='reserved', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, default=apps.storage.models.default_storage_price, help_text='Kwota ustalona przy rezerwacji. Domyslnie z STORAGE_DEFAULT_PRICE.', max_digits=8, verbose_name='Cena')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Zaplacono')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Ustawiane automatycznie, gdy wplaty pokryja cala cene.', null=True, verbose_name='Oplacone w calosci')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Przyjeto')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Wydano')),
                ('check_in_notes', models.TextField(blank=True, verbose_name='Uwagi przy przyjeciu')),
                ('check_out_notes', models.TextField(blank=True, verbose_name='Uwagi przy wydaniu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(help_text='Konkretna sztuka z tego zlecenia - rower albo sprzet zimowy.', on_delete=django.db.models.deletion.PROTECT, related_name='storage_bookings', to='customers.bike', verbose_name='Sprzet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repair_order', models.ForeignKey(help_text='Zlecenie obslugujace ten sprzet - zrodlo numeru naklejki (bike_tag_number).', on_delete=django.db.models.deletion.PROTECT, related_name='storage_bookings', to='orders.repairorder', verbose_name='Zlecenie')),
            ],
            options={
                'verbose_name': 'Przechowanie',
                'verbose_name_plural': 'Przechowania',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reserve', 'Rezerwacja'), ('check_in', 'Przyjecie'), ('check_out', 'Wydanie'), ('extend', 'Przedluzenie'), ('payment', 'Wplata'), ('cancel', 'Anulowanie')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='storage.storagebooking')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zdarzenie przechowania',
                'verbose_name_plural': 'Zdarzenia przechowania',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='storagebooking',
            index=models.Index(fields=['start_date', 'end_date'], name='storage_sto_start_d_4b1ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebooking',
            index=models.Index(fields=['bike', 'status'], name='storage_sto_bike_id_ca8311_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagebooking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='storage_booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='storagebooking',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', Decimal('0.00'))), name='storage_booking_paid_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='storagebooking',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('price'))), name='storage_booking_paid_amount_within_price'),
        ),
    ]
